
name: Continuous Integration

on:
  push:
    branches:
      - master
      - dev

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1

      - name: Install node modules
        run: |
          yarn install
          
  build-android:
    needs: install
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
          
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android App APK
        run: |
          cd android && ./gradlew assembleRelease
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
