name: Continuous Integration

on:
  push:
    branches:
      - master
      - dev

jobs:          
  build-android:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
          
      - name: Install node modules
        run: |
          yarn install

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android App APK
        run: |
          cd android && ./gradlew assembleRelease
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
          
      - name: upload artefact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ConstruFind/construfind-android
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: ConstrufindTeam
          file: android/app/build/outputs/apk/release/app-release.apk
          notifyTesters: false
          debug: false
